#!/usr/bin/env bash
# A Bash script that displays "To infinity and beyond" indefinitely and resists SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

echo "OK"

while true
do
  echo "To infinity and beyond"
  sleep 2
done
