#!/usr/bin/env bash
# A Bash script that displays "To infinity and beyond" indefinitely and resists SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
#!/usr/bin/env bash
# A Bash script that sends SIGTERM to the 7-highlander process

kill "$(pgrep -f 7-highlander)"
