#!/usr/bin/env bash
# This script kills the 7-highlander process using SIGKILL (signal 9)

# Find the PID of the 7-highlander process
PID=$(pgrep -f 7-highlander)

# Kill the process with SIGKILL
kill -9 "$PID"
