#!/bin/bash
# 8-beheaded_process
# Script to kill the 7-highlander process using SIGKILL

# Find the PID of the 7-highlander process
PID=$(pgrep -f 7-highlander)

# Kill the process with SIGKILL (signal 9)
kill -9 "$PID"
